### PR TITLE
Update laravel-debugbar.css

### PR DESCRIPTION
**Pull request by SplashZK**
Change the size of the tables
Before:
antes
After:
despues

### CODE REVIEW

**Comment by barryvdh** [comment]
I don't think that's usually the case.. do you have some conflicting cash?

**Comment by SplashZK** [comment]
i don't have css conflict, the css is loaded correctly, when i disable this property the table take the correct form.
image
i don't know if only me have this problem, maybe yes because i search in the issues section and i don't found anything related

**Comment by diogogomeswww** [comment]
I also saw that today. and was about to make a PR.

But I didn't check if that CSS is being used elsewhere.

**Comment by barryvdh** [comment]
Sorry, not really sure about this. Haven't encountered this before.

**Pull request closed without merging**
