### PR TITLE
Added numerical ordering for widgets list

### PR DESCRIPTION
**Pull request by duysolo**
Added numerical ordering for widgets list, such as: 
- Views list 
- SQL queries list

Capture

### CODE REVIEW

**Comment by duyphan2502** [comment]
@barryvdh Could you have a look on it? 
The numerical ordering is very useful for us when we have a long widgets list.

**Comment by xuandung38** [comment]
Hope approve ... soon

**Comment by sangnguyenplus** [comment]
Waiting for approval 👍

**Comment by ManojKiranA** [comment]
Adding this to Config file may be Helpful too.

I think You can add that under Config->options array

So that Users may Enable or Disable it

**Comment by sangnguyenplus** [comment]
@ManojKiranA I don't think so, it's just a small feature with some extra CSS. Don't need a configure for a simple feature like that.

**Comment by barryvdh** [comment]
What do those numbers add? You can't connect them to any index or anything?

**Pull request closed without merging**
