### PR TITLE
Upstream twig extensions

### PR DESCRIPTION
**Pull request by erikn69**
It would be an idea to remove a lot of code, and php-debugbar already left behind the old syntax
#632 
https://github.com/rcrowe/TwigBridge/blob/4c256648cdc436fdd223e08ab1b8605b6fe75896/composer.json#L18-L19

### CODE REVIEW

**Comment by barryvdh** [comment]
Is the compatibe with the old version? Or are user changes required.

**Comment by erikn69** [comment]
It should be fully compatible, 
I gave it a quick check with https://github.com/rcrowe/TwigBridge and it didn't give me any problems

**Comment by barryvdh** [comment]
Hmm I don't it always works, because of the order. The collectors are not added yet in the case I'm trying. See https://github.com/barryvdh/laravel-debugbar/pull/1600

**Comment by erikn69** [comment]
>Hmm I don't it always works, because of the order. The collectors are not added yet in the case I'm trying.

I assume that the problem was already there before this change, or did this change cause it?

**Pull request merged**
