### PR TITLE
Fix version for laravel 5.1

### PR DESCRIPTION
**Pull request by MathieuDoyon**

### CODE REVIEW

**Comment by barryvdh** [comment]
Why?

**Comment by MathieuDoyon** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - barryvdh/laravel-debugbar dev-master requires illuminate/support 5.0.* -> satisfiable by laravel/framework[5.0.x-dev], illuminate/support[5.0.x-dev, v5.0.0].
    - barryvdh/laravel-debugbar dev-master requires illuminate/support 5.0.* -> satisfiable by laravel/framework[5.0.x-dev], illuminate/support[5.0.x-dev, v5.0.0].
    - Can only install one of: laravel/framework[5.1.x-dev, 5.0.x-dev].
    - Can only install one of: laravel/framework[5.1.x-dev, 5.0.x-dev].
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework 5.1.x-dev
    - don't install illuminate/support v5.0.0|don't install laravel/framework 5.1.x-dev
    - Installation request for laravel/framework 5.1.*@dev -> satisfiable by laravel/framework[5.1.x-dev].
    - Installation request for barryvdh/laravel-debugbar dev-master -> satisfiable by barryvdh/laravel-debugbar[dev-master].

**Comment by barryvdh** [comment]
Yeah but why do you want to install laravel 5.1? Laravel 5.0 is just out a few days..

**Comment by MathieuDoyon** [comment]
Because your dev branch (master) should work with laravel/framework dev branch or tag it.

sorry if my english is not perfect.

**Comment by barryvdh** [comment]
I've made it a bit less strict: https://github.com/barryvdh/laravel-debugbar/commit/87ec9ac20309a4e24c6f44b3d10e3333b1650c48

But no, my master branch shouldn't target the latest framework master. It targets the current version, which is 5.0.

But Laravel 5 should follow SemVer and therefor work.

**Comment by MathieuDoyon** [comment]
Great, I understand.

Thank you!

**Comment by GrahamCampbell** [comment]
> But Laravel 5 should follow SemVer and therefor work.

I don't know who gave you that idea, but L5 is 100% NOT following semver.

@barryvdh Loosening the versions is a bad idea. We don't know exactly how much is going to break in 5.1 yet.

**Comment by barryvdh** [comment]
Hmm I thought Taylor said something like that. But okay, will revert it then .

**Comment by GrahamCampbell** [comment]
No, he definitely isn't going to do semver. I had a chat with him about this about 3 weeks ago.

Laravel treats minor versions as semver major versions, and uses major versions for things like architectural changes.

**Comment by barryvdh** [comment]
Reverted in https://github.com/barryvdh/laravel-debugbar/commit/30fdf8fc78eb33e2eb8b18c4b7eb6c86e38df98b

**Comment by supgeek-rod** [comment]
@barryvdh  laravel-debugbar be able to work in 5.1?

**Comment by barryvdh** [comment]
Should work. If not, create a separate issue.

**Pull request closed without merging**
