### PR TITLE
Implemented support for Twig 3

### LINKED ISSUE #13: [Proposal] Check duplicated queries
Review queries and catch duplicated ones could be very useful to track our application behavior, like [onigoetz/profiler](https://github.com/onigoetz/profiler) do.

ss

### LINKED ISSUE #1313: Compatibility for twig 3.0
On a project with Twig 3. 0 and Laravel 7.0 and higher I get this error : 

Error
Class 'Twig_Extension' not found

Which is caused by declaration of twig extensions.

Is it possible to duplicate these three functions to be compatible to twig 3.0 :
```php
'Barryvdh\Debugbar\Twig\Extension\Debug',
'Barryvdh\Debugbar\Twig\Extension\Dump',
'Barryvdh\Debugbar\Twig\Extension\Stopwatch',
```

Will try to purpose a PR soon.

### PR DESCRIPTION
**Pull request by tobias-kuendig**
This PR makes the Twig Extensions compatible with Twig 2 and 3 by conditionally extending the available base class.

Fixes #1313

### CODE REVIEW

**Comment by daftspunk** [comment]
Backwards compatibility! You're doing good work, @tobias-kuendig 

This is somewhat of a blocker. We've had to [disable Twig for now](https://github.com/rainlab/debugbar-plugin/commit/279609efa38e2e62f22f75cca20d24191c1cabfb) since Laravel 9 won't work with anything else.

**Comment by daftspunk** [comment]
Hey @barryvdh 

What's the plan, is the hybrid Twig 2/3 approach provided by @tobias-kuendig suitable? Or would you like to change this to exclusive Twig 3 support?

Apologies to pester, but we are getting some frustrated users regarding this
https://github.com/rainlab/debugbar-plugin/issues/58

Thanks for all your hard work!

**Comment by barryvdh** [comment]
I think it's probably cleaner to create 1 base extension class and use that?

**Comment by tobias-kuendig** [comment]
I have refactored the Twig compatibility check to a single base class for `Extension`, `Node` and `TokenParser`. 

Let me know if any further changes are required to this PR, @barryvdh!

**Review by barryvdh — APPROVED** [review]

**Pull request merged**
