### PR TITLE
PSR-2 and short_array_syntax fix

### PR DESCRIPTION
**Pull request by gmsantosxl**
Fixes applied with php-cs-fixer.

### CODE REVIEW

**Comment by barryvdh** [comment]
Hmm, this does make it pretty hard to keep track of the 4.2 version also (which supports 5.3)

**Comment by gmsantosxl** [comment]
But master branch isn't Laravel 5 only?

**Comment by barryvdh** [comment]
Yes so if I merge this into master, and make a fix later on, I probably can't cherry-pick that pull to the 4.2 branch.

**Comment by gmsantosxl** [comment]
Makes sense. Closing this PR

**Comment by GrahamCampbell** [comment]
I'll just do this here: https://styleci.io/.

**Comment by GrahamCampbell** [comment]
I'll just put this here: https://styleci.io/.

**Pull request closed without merging**
