### PR TITLE
Support editor link on QueryCollector/ExceptionsCollector

### PR DESCRIPTION
**Pull request by erikn69**
This PR allow us to easy open files on editor from queries widget

image

I also avoid duplicating the same code again, now it uses build-in methods
https://github.com/barryvdh/laravel-debugbar/blob/23f6174bff720bc4ecce767c07fe0a79a175eca8/src/DataCollector/RouteCollector.php#L33-L50
https://github.com/barryvdh/laravel-debugbar/blob/23f6174bff720bc4ecce767c07fe0a79a175eca8/src/DataCollector/ViewCollector.php#L22-L39

Also `getEditorHref` was removed, now it uses build-in methods

Related https://github.com/barryvdh/laravel-debugbar/pull/1258, https://github.com/barryvdh/laravel-debugbar/pull/1359,

### CODE REVIEW

**Review by angeljqv — APPROVED** [review]

**Comment by erikn69** [comment]
hi @barryvdh, ready for review,
`getEditorHref`, `replaceSitesPath`, were removed in favor of the default `getXdebugLink` method which performs the same process(also it is supported on default js widgets)

Now, 
editor can be assigned to any collector with default method  `setXdebugLinkTemplate`
replace server pathc can be assigned to any collector with default method  `setXdebugReplacements`

**Comment by angeljqv** [comment]
@barryvdh ping :)

**Comment by barryvdh** [comment]
Maybe this is a silly question, but am I supposed to configure something before this works?
I'm using Laravel Herd, but the editor links all point to `/app/`, `/resources` or `/vendor`. Do I need to add the base_path somewhere? According to the config it should work for local development?

**Comment by erikn69** [comment]
Hi, on config, `local_sites_path`, `remote_sites_path` existed, I delegated them to the main package(`xdebuglink`)
https://github.com/barryvdh/laravel-debugbar/blob/04b28687714922dff6a7423274089c0c685f18c1/src/LaravelDebugbar.php#L1225-L1230

**Comment by barryvdh** [comment]
Yeah but with the default config, it redirects to the project file link, not the existing one (eg /User/Barry/etc)
image

**Comment by barryvdh** [comment]
The path in the view is correct, but the link should be the real path, right?

**Comment by barryvdh** [comment]
Or did I merge it incorrectly? (Had some conflicts)

**Comment by erikn69** [comment]
Sorry, i was on lunch, I'll try it and send a fxi if something is failing

**Comment by erikn69** [comment]
**Queries**
image

**Views**
image

----
config/debugbar.php
```php
  ///
  'local_sites_path' => env('DEBUGBAR_LOCAL_SITES_PATH', ''),
  ///
```
.env
```properties
DEBUGBAR_LOCAL_SITES_PATH=C:\laravel\ssw
```
@barryvdh  `local_sites_path` already exists before my changes

**Comment by barryvdh** [comment]
But wouldn't it make more sense that value is the base_path() by default already?

**Comment by erikn69** [comment]
yes, it would

**config/debugbar.php**
```php
'local_sites_path' => env('DEBUGBAR_LOCAL_SITES_PATH', base_path()),
```

**Comment by barryvdh** [comment]
Yes fixed the config in #1506 and showed just the filename to shorten a bit in #1505 
Thanks!

**Pull request merged**
