### PR TITLE
Move route definition into separate file - v2

### PR DESCRIPTION
**Pull request by fletch3555**
Fixed issue reported in #1050

### CODE REVIEW

**Comment by barryvdh** [comment]
So did you test this?

**Comment by fletch3555** [comment]
Quick response...

Apologies, I had missed something.  The use of $this->app() does not work in certain circumstances.  Do you prefer using facades (`Config`, `Route`) or helper methods (`config(...)` or `app('config')`, `app('route')`)?

**Comment by fletch3555** [comment]
Just following up on this.  Any opinions on my question, @barryvdh ?

**Comment by fletch3555** [comment]
@barryvdh thanks for the merge, but I had an outstanding question.  Just curious if you prefer `config(...)` or `app('config')`?  There's one scenario where this won't work as-is.  I'll open another PR with the fix,

**Pull request merged**
