### PR TITLE
Avoid `Undefined variable $sessionManager`

### PR DESCRIPTION
**Pull request by erikn69**
image

### CODE REVIEW

**Comment by erikn69** [comment]
@barryvdh hi, #1662 seems to break ajax capture too

**Comment by barryvdh** [comment]
Yeah probably going to revert that.

**Comment by barryvdh** [comment]
See https://github.com/barryvdh/laravel-debugbar/pull/1666
Which case is for ajax?

**Comment by erikn69** [comment]
ajax  seems to be working👍

**Pull request closed without merging**
