### PR TITLE
Uncaught TypeError: PhpDebugBar.Widgets.TemplatesWidget is not a cons…

### PR DESCRIPTION
**Pull request by ghost**
…tructor fix

### CODE REVIEW

**Comment by gduymaz** [comment]
Uncaught TypeError: PhpDebugBar.Widgets.TemplatesWidget is not a constructor fixed

**Comment by barryvdh** [comment]
I haven't encountered this, is this still happening?

**Comment by deleugpn** [comment]
quite ironic that @barryvdh closed this 5 days ago, which totally makes sense (the ticket is from 2020 😂), and I'm getting this error now

**Comment by barryvdh** [comment]
Could be related to https://github.com/barryvdh/laravel-debugbar/pull/1519
Are you on the latest version of both php-debugbar and laravel-debugbar?

**Comment by erikn69** [comment]
reload browser cache(`Ctrl + Shift + R`)

**Pull request closed without merging**
