### PR TITLE
Remove .pull-left, .pull-right from FA css

### PR DESCRIPTION
**Pull request by tomlankhorst**
Avoid polluting CSS's 'global namespace'.
#855

### CODE REVIEW

**Comment by SlyDave** [comment]
Just remove them isn't enough? Isn't the Debug bar using these classes. If you remove them and aren't using bootstrap 3. The Debug bar won't display correctly?

**Comment by tomlankhorst** [comment]
A `grep` on the source does not show usages:

```
➜  laravel-debugbar git:(master) grep -ri "pull-right" .
./src/Resources/vendor/font-awesome/style.css:.pull-right {
./src/Resources/vendor/font-awesome/style.css:.phpdebugbar-fa.pull-right {
➜  laravel-debugbar git:(master) grep -ri "pull-left" .
./src/Resources/vendor/font-awesome/style.css:.pull-left {
./src/Resources/vendor/font-awesome/style.css:.phpdebugbar-fa.pull-left {
```

**Comment by crashkonijn** [comment]
Came here to ask for this, we just spent an hour trying to figure out why the site looked different on production with the exact same files.

Nice work!

**Comment by tomlankhorst** [comment]
@crashkonijn Been there ;).

**Pull request merged**
