### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by ekvedaras**
Colors used: https://tailwindcss.com/docs/customizing-colors/#default-color-palette

Screenshot 2020-08-01 at 19 39 10
Screenshot 2020-08-01 at 19 39 04
Screenshot 2020-08-01 at 19 37 51
Screenshot 2020-08-01 at 19 38 03
Screenshot 2020-08-01 at 19 36 03
Screenshot 2020-08-01 at 19 36 50
Screenshot 2020-08-01 at 19 37 07

### CODE REVIEW

**Comment by ekvedaras** [comment]
Maybe it should be made optional in case some people want to force specific version for any reason? There could be a config option something like this `'theme' => 'auto', // auto, dark, light`

**Comment by barryvdh** [comment]
I like this idea. I would prefer it to be optional indeed, perhaps auto is a good default.

**Comment by ekvedaras** [comment]
So this change required to duplicate css for dark mode. One for `.dark` and one for `.dark-auto`. I tried to optimize the CSS as much as possible but it is still quite some lines.

There is another way to do it though. We could keep only `.dark` variant in CSS (so no duplicates) and use JS to detect dark/ligt mode changes and apply/remove `.dark` class. If you prefer that option I can push it.

If there is a better way to add classes to debugbar please tell me and I will update :)

**Comment by ekvedaras** [comment]
Here is the other option https://github.com/barryvdh/laravel-debugbar/compare/master...ekvedaras:dark-mode-js

However, both options have one small drawback. Since the classes are added with javascript and it is done after debug bar is initialized, sometimes you can see the light version for a split second. I don't know if there is a way to do that before it is rendered. Maybe modify debug bar content itself before attaching to the request 🤔

**Comment by ekvedaras** [comment]
Or.. we may have separate CSS files for dark mode and add them conditionally. Just then again duplicate versions are needed. Unless, https://www.w3schools.com/cssref/pr_import_rule.asp this is a thing and it works in plain css :D

**Comment by ekvedaras** [comment]
OK, so I've pushed another version of it. This one has no problems with flickering modes on page refresh and only has one CSS file for dark mode to maintain. The only hacky thing was media start and end files, but I think it's a pretty small price to pay.

**Comment by barryvdh** [comment]
I added the Dracula theme for HighlightJS, I think that's a bit more readable/easier to the eyes. What do you think?

image

**Comment by sebdesign** [comment]
The duplicate SQL queries background color needs to be inverted too.

image

**Comment by barryvdh** [comment]
Can either of you submit a PR?

**Comment by sebdesign** [comment]
I'm at work now so I can't work on this until the evening.

**Comment by barryvdh** [comment]
Something like this?
image

**Comment by barryvdh** [comment]
Or more yellow/brownish perhaps:
image

**Comment by ekvedaras** [comment]
Since it's meant to indicate duplicates, I think the yellow one grabs attention better

**Comment by ekvedaras** [comment]
I guess for this color, widget text should be adjusted 
image

**Comment by ekvedaras** [comment]
Gray 500 looks better:

image


```css
div.phpdebugbar div.phpdebugbar-widgets-exceptions li.phpdebugbar-widgets-list-item.phpdebugbar-widgets-sql-duplicate span.phpdebugbar-widgets-filename,
div.phpdebugbar div.phpdebugbar-widgets-sqlqueries li.phpdebugbar-widgets-list-item.phpdebugbar-widgets-sql-duplicate span.phpdebugbar-widgets-database,
div.phpdebugbar div.phpdebugbar-widgets-sqlqueries li.phpdebugbar-widgets-list-item.phpdebugbar-widgets-sql-duplicate span.phpdebugbar-widgets-duration,
div.phpdebugbar div.phpdebugbar-widgets-sqlqueries li.phpdebugbar-widgets-list-item.phpdebugbar-widgets-sql-duplicate span.phpdebugbar-widgets-memory,
div.phpdebugbar div.phpdebugbar-widgets-sqlqueries li.phpdebugbar-widgets-list-item.phpdebugbar-widgets-sql-duplicate span.phpdebugbar-widgets-row-count,
div.phpdebugbar div.phpdebugbar-widgets-sqlqueries li.phpdebugbar-widgets-list-item.phpdebugbar-widgets-sql-duplicate span.phpdebugbar-widgets-copy-clipboard,
div.phpdebugbar div.phpdebugbar-widgets-sqlqueries li.phpdebugbar-widgets-list-item.phpdebugbar-widgets-sql-duplicate span.phpdebugbar-widgets-stmt-id {
    color: var(--color-gray-500);
}
```

**Comment by sebdesign** [comment]
I think `--color-gray-600` is nicer for the background. That brownish/poop doesn't look nice with the Dracula theme or Laravel colors.

**Comment by sebdesign** [comment]
I'd prefer `--color-gray-600` but the yellow doesn't look that good against Dracula theme or Laravel colors.

**Pull request merged**
