### PR TITLE
Remove deprecated TwigCollector

### PR DESCRIPTION
**Pull request by erikn69**
`TwigCollector` is deprecated 
[maximebf/php-debugbar/src/DebugBar/Bridge/Twig/TwigCollector.php#L30](https://github.com/maximebf/php-debugbar/blob/6cfc9ae6834adc9ac45f3bc81f1e6048a3d08103/src/DebugBar/Bridge/Twig/TwigCollector.php#L30)

### CODE REVIEW

**Comment by barryvdh** [comment]
Hmm tests seem not to happy about this.

**Comment by erikn69** [comment]
Works on a real app, but for tests, that path not exists

base_path has
- vendor
. laravel-debugbar
. php-debugbar

But on test
- laravel-debugbar
 . vendor/php-debugbar

Maybe using `ReflectionClass`, I'm going to try it

**Comment by barryvdh** [comment]
Do we need the path? In the other collectors that isn't used?

**Comment by erikn69** [comment]
>Do we need the path? In the other collectors that isn't used?

Yes, Extends TwigCollector only because original php-debugbar path cannot be accessed, 
It would be better if there was a way to declare that it should take the original path and not the overwritten one, like a flag

**Comment by erikn69** [comment]
>Do we need the path? In the other collectors that isn't used?

You are right, not needed, At first it gave me a problem, but maybe it was the browser

**Pull request merged**
