### PR TITLE
Make service provider deferrable to allow for custom (filesystem) service provider

### PR DESCRIPTION
**Pull request by PrinsFrank**
As described on a [similar PR in the ide-helper](https://github.com/barryvdh/laravel-ide-helper/pull/914), when a serviceprovider is not deferrable, the service provider of a package is registered before any custom service providers in a project are registered.

I am currently working on a project with a custom FileSystemServiceProvider, where requiring the debugbar causes an error in Container.php on line 879 `Target class [files] does not exist` and Container.php on line 877 `Class "files" does not exist`. This issue was also mentioned in #1112.

<details>
    <summary>Simplest bug reproduction in code</summary>

## ./app/Providers/CustomFileSystemProvider.php

```php
<?php
declare(strict_types=1);

namespace App\Providers;

use Illuminate\Filesystem\FilesystemServiceProvider;

class CustomFileSystemServiceProvider extends FilesystemServiceProvider
{
    // Overwrite anything in here, or keep this empty for a simple reproduction
}
```

## ./config/app.php

```php
'providers' => [
    //Illuminate\Filesystem\FilesystemServiceProvider::class,
    App\Providers\CustomFileSystemServiceProvider::class,
```
</details>

This PR adds the DeferrableProvider interface to the package's service provider, and adds the provided services to a `provides` method so these services can be registered when needed.

### CODE REVIEW

**Comment by caimaxtingle** [comment]
+1 also getting this issue, please approve asap

**Comment by PrinsFrank** [comment]
@barryvdh Can you look at this PR?

**Comment by PrinsFrank** [comment]
@barryvdh Can this get merged? Our team has been running on this fork since november with no issues, and there are is also someone else running into this issue in #1306.

**Comment by PrinsFrank** [comment]
As #1197 is now merged I'll close this PR.

**Pull request closed without merging**
