### PR TITLE
Add Lumen collector

### PR DESCRIPTION
**Pull request by vojtasvoboda**
Add Lumen collector. Tested with latest Lumen 5.4.1.

snimek obrazovky 2017-01-30 v 20 45 09

### CODE REVIEW

**Comment by barryvdh** [comment]
Isn't it easier to use the laravel collector for this?

**Comment by vojtasvoboda** [comment]
I've tried Laravel collector, but it didn't work. Laravel is using `Illuminate\Foundation\Application` and Lumen is using `Laravel\Lumen\Application` as application container.

**Comment by vojtasvoboda** [comment]
And Lumen Application doesn't have `$app->getLocale()`.

**Comment by barryvdh** [comment]
I think we should update the Laravel controller to work with Lumen correctly.

**Pull request closed without merging**
