### PR TITLE
Support Auto-Discovery

### PR DESCRIPTION
**Pull request by taylorotwell**
This will make the package work with auto-discovery in Laravel 5.5. Enjoy :)

### CODE REVIEW

**Comment by Francismori7** [comment]
No way that's awesome!!

**Comment by barryvdh** [comment]
Thanks!

**Comment by barryvdh** [comment]
@taylorotwell I tagged this as `v2.4.0`. So if you want you could updated your blog post(https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518)
to use remove `dev-master`, or perhaps better even: `composer require barryvdh/laravel-debugbar --dev`, to install it in dev only :)

**Comment by lukepolo** [comment]
Although early, will there be a way to disable this autoloading?

```
Use case :  
I only want to add the service provider / facade in development only 
```

guess we may have to wait till 5.5 is released to find out that answer

**Comment by barryvdh** [comment]
See my comment above, when you require with - - dev it is only installed and loaded on dev.

**Comment by pk-informatics** [comment]
@lukepolo you can also disable autoloading - see the highlighted part in taylors blogpost about autoloading: https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518

**Comment by lukepolo** [comment]
Yup thank you , missed those parts shouldn't have skimmed it

**Comment by mikimaine** [comment]
What if I want to disable it only for testing some things without removing it completely?  Currently, I can go to app.php and comment out the service provider.

**Comment by barryvdh** [comment]
Debugbar only loads when debug = true

**Comment by mikimaine** [comment]
Ya for debug bar package there is that ENV value. What I want to know is for other packages, How will the auto discovery handles that.

**Comment by barryvdh** [comment]
You can disable it, see the blog

**Comment by marktopper** [comment]
@mikimaine 
image

**Comment by cheerego** [comment]
Such nice feature 😀😀😀

**Comment by adampatterson** [comment]
Nice, should also help with updates/upgrades when your plopping configs between projects.

**Comment by nelson6e65** [comment]
Hmmm... it's nice is loaded only in local development, but.. what about aliases usage?

For example, in my code I can use the `Debugbar` facade alias, for its methods. So, in production **it will not trigger a non-existent class error?**

I'm still have to check if I'm on local or production in order to use it. So, it needs to be available on production, even if it is disabled. u.u

**Comment by barryvdh** [comment]
You shouldnt leave those calls in your production code, no.

**Pull request merged**
