### PR TITLE
add cache tab

### PR DESCRIPTION
**Pull request by adelf**
cache-tab

### CODE REVIEW

**Comment by decadence** [comment]
https://github.com/barryvdh/laravel-debugbar/issues/634

**Comment by barryvdh** [comment]
Why are you serializing the values?

**Comment by adelf** [comment]
mm.. I did it week ago. I didn't like something when there was pure values. I'll check it on Monday.

**Comment by adelf** [comment]
I tried without serialize and get '[object Object]' for each class which stored in cache. Thats not very informative. I wanted to see what exactly goes to cache. But I used laravel-debug-bar 2.2. Maybe in current version it's much better? (as I see there are VarDumpers instead of ValueExporters)
Anyway, @barryvdh it's up to you. I can remove serializing, or make it optional...

**Comment by barryvdh** [comment]
It should use the vardumper indeed, similar to the message or view objects.

**Comment by adelf** [comment]
Yes. I misunderstood something. Fixed. Thanks.

**Comment by barryvdh** [comment]
Thanks

**Comment by decadence** [comment]
Thanks

**Comment by barryvdh** [comment]
I pulled this in branch 2.4

**Comment by adelf** [comment]
Yes. It should support all 5.* versions.

**Pull request merged**
