### PR TITLE
Update composer commands with version

### PR DESCRIPTION
**Pull request by sicaboy**
for branch 2.4

### CODE REVIEW

**Comment by aik099** [comment]
👎 , because this command would prevent 3.x version from being used with Laravel 5.5.

**Comment by sicaboy** [comment]
Well. This change is just for Branch 2.4. If you run this command without :~2.4, it downloads the latest version.

**Comment by aik099** [comment]
Ups, haven't noticed the target PR branch. My apologies.

**Comment by barryvdh** [comment]
Yeah it's a bit unclear sometimes, can't even see it on mobile view.

**Pull request merged**
