### PR TITLE
service provider route from boot to register

### PR DESCRIPTION
**Pull request by pbellerive**
Hi, 

I have move the route in the service provider from the boot method to the register method. 

In Laravel the boot method occur at the end of everything. 

The process is register everything and boot . So by adding your route in the boot, we can't tweak the precedence of register with the package by registring in order. 

SO , actually we have the problem. Can you validate en merge.

### CODE REVIEW

**Comment by barryvdh** [comment]
What is your use-case?

**Comment by pbellerive** [comment]
I have a kind of catch all.  Even if i register the debugbar before anything i Stiller fall in thé catch all because you registre route in thé boot method


Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.

-------- Message d'origine --------
De : "Barry vd. Heuvel" <notifications@github.com> 
Date : 16-10-19  10:54 AM  (GMT-05:00) 
À : barryvdh/laravel-debugbar <laravel-debugbar@noreply.github.com> 
Cc : pbellerive <p.bellerive@gmail.com>, Author <author@noreply.github.com> 
Objet : Re: [barryvdh/laravel-debugbar] service provider route from boot to
&nbsp; register (#556) 

What is your use-case?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/barryvdh/laravel-debugbar","title":"barryvdh/laravel-debugbar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/barryvdh/laravel-debugbar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@barryvdh in #556: What is your use-case?"}],"action":{"name":"View Pull Request","url":"https://github.com/barryvdh/laravel-debugbar/pull/556#issuecomment-254837686"}}}

**Comment by barryvdh** [comment]
Did you fix this? Or why close it?

**Comment by pbellerive** [comment]
After research its m'y bad. 
In 5.3 we doNT put route in registre but in boot


Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.

-------- Message d'origine --------
De : "Barry vd. Heuvel" <notifications@github.com> 
Date : 16-10-19  4:08 PM  (GMT-05:00) 
À : barryvdh/laravel-debugbar <laravel-debugbar@noreply.github.com> 
Cc : pbellerive <p.bellerive@gmail.com>, State change <state_change@noreply.github.com> 
Objet : Re: [barryvdh/laravel-debugbar] service provider route from boot to
&nbsp; register (#556) 

Did you fix this? Or why close it? 

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/barryvdh/laravel-debugbar","title":"barryvdh/laravel-debugbar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/barryvdh/laravel-debugbar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@barryvdh in #556: Did you fix this? Or why close it? "}],"action":{"name":"View Pull Request","url":"https://github.com/barryvdh/laravel-debugbar/pull/556#issuecomment-254925704"}}}

**Pull request closed without merging**
