### PR TITLE
[L5] Fix for crash when attempting to explain non-mysql queries

### PR DESCRIPTION
**Pull request by FractalizeR**
Currently only MySQL queries are supported for EXPLAIN so... (I work with Postgres).

### CODE REVIEW

**Comment by barryvdh** [comment]
So why not just not enable it? :P

**Comment by GrahamCampbell** [comment]
Also, this doesn't work. You could be using multiple drivers.

**Comment by GrahamCampbell** [comment]
We can't assume the default driver is used for eveything.

**Comment by FractalizeR** [comment]
@barryvdh Well, it was enabled by default in settings :) If we support only MySQL-like EXPLANs, I think there is no need to cause an error trying to parse unparseable data. It is not really obvious that only MySQL is supported, otherwise there will be a crash.

@GrahamCampbell Good catch. Missed that. Should I fix it?

**Comment by barryvdh** [comment]
It shouldn't be enabled by default: https://github.com/barryvdh/laravel-debugbar/blob/50ca2243bd38fedd2b4c9314068f7f06b79602d4/config/debugbar.php#L126

**Pull request closed without merging**
