### PR TITLE
Use 1.14 version of php-debugbar

### LINKED ISSUE #706: Make 2.4.x release with 1.14 version of php-debugbar
Please make 2.4.x release, that is compatible with Laravel 5.4 and is using php-debugbar 1.14 version with latest fixes (e.g. showing used PHP version).

### PR DESCRIPTION
**Pull request by aik099**
Closes #706

### CODE REVIEW

**Comment by kiran-jose** [comment]
This update is causing issue for us. We have added `barryvdh/laravel-debugbar` in `require-dev` section of `composer.json` file.
It is working fine in local. But it is causing issue in server on running `composer update --lock --no-dev --no-scripts -vv`.

Following error is shown on run the above update command in server:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barryvdh/laravel-debugbar (locked at 2.4.x-dev, required as ^2.4@dev) -> satisfiable by barryvdh/laravel-debugbar[2.4.x-dev].
    - barryvdh/laravel-debugbar 2.4.x-dev requires maximebf/debugbar ~1.14.0 -> satisfiable by maximebf/debugbar[1.14.x-dev, v1.14.0].
    - Can only install one of: maximebf/debugbar[1.14.x-dev, 1.13.1].
    - Can only install one of: maximebf/debugbar[v1.14.0, 1.13.1].
    - Installation request for maximebf/debugbar (locked at 1.13.1) -> satisfiable by maximebf/debugbar[1.13.1].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```

@aik099 how can I resolve this issue?

**Comment by aik099** [comment]
The `composer update --lock` command AFAIK doesn't update packages but only changes `composer.lock` file.

Maybe you have some dependencies to `maximebf/debugbar` package in your composer.json that overrides versions that Laravel DebugBar wants (the `maximebf/debugbar (locked at 1.13.1) ` line suggests it).

**Comment by kiran-jose** [comment]
Thanks @aik099. Removing the `--lock` option fixed the issue. 
But I still don't understand why `--lock` caused the problem.

**N.B.**: there is no other dependencies that requires `maximebf/debugbar` package
**P.S.**: Composer documentation given in - https://getcomposer.org/doc/03-cli.md says that: `--lock: Only updates the lock file hash to suppress warning about the lock file being out of date.`

**Comment by barryvdh** [comment]
On your production server, always commit the lock file and run `composer install`, that will give you the exact same thing as on local.

**Pull request merged**
