### PR TITLE
Add Xdebug Link functionality

### PR DESCRIPTION
**Pull request by amenk**
https://github.com/barryvdh/laravel-debugbar/issues/566

### CODE REVIEW

**Comment by amenk** [comment]
see https://github.com/maximebf/php-debugbar/pull/303

**Comment by aik099** [comment]
Would be great feature, once merged. Right now in traces (see image below) I see exact name of file and line where to go, but clicking on it does nothing. Would be great if it would open that file in PhpStorm automatically.



Also we should think of path mapping, because I have Laravel running inside VM where paths are `/home/username/web/project-name`, but PhpStorm is running locally, where paths are `/Volumes/web/project-name`.

**Comment by amenk** [comment]
Path mapping should usually be handled by the IDE. PhpStorm has a configuration for that.

**Comment by aik099** [comment]
It has mapping, when debugging connection comes in. But do they work, when you have link like `phpstorm://....` with path on VM?

**Comment by amenk** [comment]
The mapping is configuration wise not bound to debugging. It says in general "mapping" ... so it should :) I do not see this mapping logic to be a part here in the PHP project.

**Comment by aik099** [comment]
OK. Then I guess we need to wait and see this merged.

**Comment by decadence** [comment]
phpstorm:// works only on Mac.
For cross platform: `"http://localhost:63342/api/file/{$file}:{$line}"`

**Comment by aik099** [comment]
Just checked and path mapping has no effect. Reported issue for PhpStorm: https://youtrack.jetbrains.com/issue/WI-37690

**Comment by aik099** [comment]
The JetBrains team (PhpStorm developers) confirmed, that path mapping is only for debugging, not for remote links.

**Pull request merged**
