### PR TITLE
Show dataset tab

### PR DESCRIPTION
**Pull request by barryvdh**
Replaces the dropdown with a tab. Optional and currently disabled by default, but can be marked as default in the future.

Most important benefits:
 - More details then the dropdown
 - Toggle autoshow from front-end (much requested)
 - Filter/search history
 - See highlights (eg. number of queries)
 
image

See https://github.com/maximebf/php-debugbar/pull/627
(Needs a new release upstream though)

### CODE REVIEW

**Comment by erikn69** [comment]
Make many ajax calls and then scroll
https://github.com/maximebf/php-debugbar/pull/637#issuecomment-2013743899

**Comment by barryvdh** [comment]
Upstream is tagged, layout is slightly changed, it just adds the history badge besides the dropdown.
image

**Comment by barryvdh** [comment]
> Make many ajax calls and then scroll [maximebf/php-debugbar#637 (comment)](https://github.com/maximebf/php-debugbar/pull/637#issuecomment-2013743899)




I think this is fixed with the css change to padding now.

**Comment by DanielSpravtsev** [comment]
@barryvdh I manifest on `autoshow toggle` feature for a years (since Livewire came out with it's polling, that open new debugbar page on every request)

Just came here to say you very very very big thank you! Unbelievable very muuuchhh appreciated! ❤️ 

Years of working with `@production wire.poll @endproduction` seems to have come to an end 😄

**Pull request merged**
