### PR TITLE
Telescope compatibility 

### PR DESCRIPTION
**Pull request by barryvdh**
- Disable Telescope on Debugbar routes
- Disable Debugbar op Telescope routes

### CODE REVIEW

**Comment by barryvdh** [comment]
Yes it will not throw an error, because of the class_exists check.

**Comment by johanvanhelden** [comment]
@barryvdh when are you planning to release this?

**Comment by barryvdh** [comment]
Not really sure because Telescope is still in beta I think. But probably could be released already. The config is something everyone can add already.

**Comment by barryvdh** [comment]
@themsaid Do you think this is the most reliable way to disable Telescope, or could debugbar be ignored on the side of Telescope? Or a config flag?

**Comment by johanvanhelden** [comment]
I've taken a look at the Telescope source, but it does not look like it has a `serving` method like Nova does. So that makes disabling the Debugbar from Telescope a bit difficult. Nor does it seem to have a blacklist like Debugbar.

**Pull request merged**
