### PR TITLE
add db query length limit option

### PR DESCRIPTION
**Pull request by devypt**

### CODE REVIEW

**Comment by barryvdh** [comment]
Wouldn't it be better to update the layout to make it fit better, or to substr the parameters instead (eg. for 100 ids in a whereIn)

**Comment by devypt** [comment]
I agree with substr the params suggestion , i will push commit for this.

**Comment by aik099** [comment]
During query parameter substitution we can see if an array is coming in and display only first X entries and `...` after that. That would break query (if user decides to execute it by hand), but surely would save lots of space.

@devypt , any update?

**Comment by barryvdh** [comment]
Or should we do something with css? To truncate long queries, but show the entire thing of hover?

**Pull request closed without merging**
