### PR TITLE
Fix htmlentities PHP warning

### PR DESCRIPTION
**Pull request by jakubdibala**
Hi,

this commit fixes PHP Warning on PHP 8.1, when $binding is not a string.

### CODE REVIEW

**Review by VirusEcks — APPROVED** [review]

**Comment by davejamesmiller** [comment]
The warning this fixes (for me at least) is:

> htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in .../vendor/barryvdh/laravel-debugbar/src/DataFormatter/QueryFormatter.php on line 58

I was going to suggest a slightly different change that only handles nulls:

```
            if ($binding !== null) {
                $binding = htmlentities($binding, ENT_QUOTES, 'UTF-8', false);
            }
```

That way no other unsafe parameters can slip through (a class that might implement `__toString()`, for example)... Though I don't know if that's likely to be an issue in practice.

**Comment by fredsal** [comment]
Closes #1296

**Comment by pionl** [comment]
We are running this for past 28 days without problem 👍

**Comment by fredsal** [comment]
@pionl we have to wait for @barryvdh

**Comment by barryvdh** [comment]
See https://github.com/barryvdh/laravel-debugbar/pull/1291#issuecomment-1036792934
I'd prefer to make sure it's safer. It's only for outputting.

**Comment by nmiyazaki-chapleau** [comment]
@barryvdh Any plans on tagging this? Currently can't pull this change because it's stuck to 3.6.7. Thanks!

**Comment by erikn69** [comment]
@barryvdh please release this 🙏

**Comment by ahmedsayedabdelsalam** [comment]
> > @barryvdh please release this 🙏
> 
> @barryvdh +1

+1

**Pull request merged**
