### PR TITLE
Complete redesign of the DebugBar (CSS only)

### PR DESCRIPTION
**Pull request by TristanMouchet**
Hey,

I was finding the bar messy and not very intuitive, this CSS update is improving [a lot] the overall look of the bar and its features.

Hope you like it!

### CODE REVIEW

**Comment by barryvdh** [comment]
Thanks, do you have a screenshot?

**Comment by TristanMouchet** [comment]
Here are some screenshots. :)
debug-bar-1
debug-bar-2
debug-bar-3
debug-bar-4
debug-bar-5
debug-bar-6
debug-bar-7
debug-bar-8
debug-bar-9

I saw there are some issues with Internet Explorer, I will check what's wrong.

**Comment by TristanMouchet** [comment]
Internet Explorer issues are due to a JavaScript error on the original phpdebugbar, so once this is fixed, it should be alright.

https://github.com/maximebf/php-debugbar/pull/441

**Comment by barryvdh** [comment]
Thanks! Overall I like this, a lot cleaner :)

Few points I'm not sure about:
 - Why is there a grey line above the red border. Is that by design still?
image

- I'm not sure if I'm a big fan of the 'well' like header, I think that it look cleaner before (and more minimal).
image

- I see you made the tables/rows more consistent, but I think without the borders, we might need to make the contrast a bit bigger between odd/even? What do you think? (Same goes perhaps for the hovers)
image

But overall very happy with this :) Let me know if you can do something with these suggestions, or otherwise I'll take a stab at it myself.

**Comment by TristanMouchet** [comment]
Here we go:

debug-bar-10

debug-bar-11

**Comment by barryvdh** [comment]
Ah, nice! The things I pointed out look much better now, thanks!

Is this good to merge?

**Comment by TristanMouchet** [comment]
Yep all good now. :)

**Comment by barryvdh** [comment]
FYI, feedback overall is positive :)
https://twitter.com/barryvdh/status/1250695650548895745

Just tweaked some small things with some custom collectors and text-shadows.

**Pull request merged**
