### PR TITLE
Use dark theme by default

### PR DESCRIPTION
**Pull request by barryvdh**
In my opinion, the dark theme is better, even without having the website in dark mode. Thoughts?

### CODE REVIEW

**Comment by erikn69** [comment]
For most dark themes are better, but it is configurable, 
and this is a debug-only package, it's not like it's for the public

**Comment by cotiga** [comment]
I don't like dark mode, please give us the choice and leave light mode as default...
Personally, I'm tired of having to waste my time all the time with the whims of the devs :p

**Comment by barryvdh** [comment]
You can set is with config or an env though?

**Comment by barryvdh** [comment]
See #1594

**Pull request merged**
