### PR TITLE
Adds option for requirejs compatibility

### PR DESCRIPTION
**Pull request by drewrichards**
Adds an option to output the debugbar javascript in a way that is compatible with requirejs. Solves the problem noted here: https://github.com/barryvdh/laravel-debugbar/issues/105. 

It works by:
- Adding a route to a javascript file that contains all the debugbar js in AMD format
- Wrapping the generated javascript in a require call that loads the debugbar module

In addition to setting the requirejs_compatible option in config/debugbar.php it is also necessary to add a path to `debugbar-all` in the requirejs config. Locally I put javascript in `public/js` and my baseUrl is `/js` so my path entry looks like `"debugbar-all": "../_debugbar/assets/debugbar"`.

### CODE REVIEW

**Comment by barryvdh** [comment]
Hmm, is this something we can do upstream in https://github.com/maximebf/php-debugbar ?

**Comment by igorrynkovoy** [comment]
Up.

**Comment by barryvdh** [comment]
Can we do this without PHP routing in php-debugbar core? I'm interested in improving, but not really sure what the best way is.

**Comment by barryvdh** [comment]
See this commit: https://github.com/maximebf/php-debugbar/commit/c3268ca12248485a56d8fadf6489a277ef40d2e9

I've added an option to render the debugbar as requirejs module, I changed it to explicitly use a name. We need to reflect these changes here, but I guess that would do the trick?

**Comment by barryvdh** [comment]
Closing due to conflicts and recent changes. Please raise an issue if this is still relevant.

**Pull request closed without merging**
