### PR TITLE
Adding of messages can be chained

### LINKED ISSUE #1376: Feature: create a chain
In my opinion, it will be helpful
`debugbar()->info($var1)->warning($var2);`
Tnx!

### PR DESCRIPTION
**Pull request by alex-i07**
fixes #1376[](https://github.com/barryvdh/laravel-debugbar/issues/1376)

Allow to call `debugbar()->emergency('message #1')->alert('message #2')->critical('message #3')`.

### CODE REVIEW

**Review by erikn69 — COMMENTED** [review]
What about this??
https://github.com/barryvdh/laravel-debugbar/blob/27b088aaad2adba74a7a73a47cb8d11277b551e3/src/Facades/Debugbar.php#L7-L20
https://github.com/barryvdh/laravel-debugbar/blob/27b088aaad2adba74a7a73a47cb8d11277b551e3/src/LaravelDebugbar.php#L48-L56

**Comment by aivanov07** [comment]
Do you mean messages must be added like this `debugbar()->alert('1st message', '2nd message', '3rd message');`?
Assume several messages must be added and each is different psr-3 level, in this case chaining looks cleaner then call each one in new line

**Comment by aivanov07** [comment]
> I'm not talking about that, I'm talking about the return void, that must be return LaravelDebugbar
without that IDEs give "alert" method not found on debugbar()->emergency('message #1')->alert('message #2')

Sorry for my misunderstanding. I fixed that.

**Comment by barryvdh** [comment]
yes we follow psr/log for this.

**Pull request closed without merging**
