### PR TITLE
Support phpredis php extension

### PR DESCRIPTION
**Pull request by Except10n**

### CODE REVIEW

**Comment by barryvdh** [comment]
Is this backward compatible with older versions?

**Comment by Except10n** [comment]
yes, [framework/src/Illuminate/Redis/Connections/Connection.php](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Redis/Connections/Connection.php) added after 5.4

**Comment by barryvdh** [comment]
But it still needs to work pre-5.4

**Comment by Except10n** [comment]
```
if (is_a($client, 'Illuminate\Redis\Connections\Connection', false)) {
    $client = $client->client();
}
```
It works fine in pre-5.4
But [php-debugbar](https://github.com/maximebf/php-debugbar/pull/319) still need to be modified, it only support predis client or interface

**Pull request merged**
