### PR TITLE
Allow enabling/disabling DebugBar from middlewares

### PR DESCRIPTION
**Pull request by aik099**
What was done:

1. moved route protection code (throws http 500 exception) into base controller constructor (reduced code duplication + auto protect any new controller actions)
2. adjust route protection to also work in Lumen (accessing to `$this->app` causes an error)
3. combined `is enabled` logic from 3 places (`LaravelDebugbar::modifyResponse` method, `LaravelDebugbar::isEnabled` method, `ServiceProvider::boot` method) into `LaravelDebugbar::isEnabled` method
4. moved code, that boots/enables DebugBar into middleware to allow easy manipulation (e.g. enable/disable on the fly) from other middlewares
5. routes are now always registered but protected in case, when accessed on disabled debugbar
6. middleware is now always registered but decides what to do based on enabled state of debugbar

With made changes it's possible to set `debugbar.enabled` or `app.debug` from any of application middlewares and DebugBar's middleware would respect that and enable/disable accordingly.

Should solve usecases from:

* #617 - no tricks, just app middleware
* #700 - app middleware that checks user access level
* #708 - service provider is always loaded, but app middleware would decide if DebugBar actually works

// cc: @robindirksen1, @younus93, @ashgibson

### CODE REVIEW

**Comment by barryvdh** [comment]
Should we throw regular 404s instead of 500?

**Comment by aik099** [comment]
> Should we throw regular 404s instead of 500?

Sure. I was actually using 404 at first, but then saw 500 being used and decided to use them instead.

Changing now.

**Comment by barryvdh** [comment]
Yeah but it wasn't registered in the first place before, so was still giving 404

**Comment by aik099** [comment]
Changed.

**Comment by barryvdh** [comment]
Should we use the Middleware function of the controller, if you want to change it on runtime?

**Comment by aik099** [comment]
We probably can create middleware using `$app['debugbar']->isEnabled()` and use `middleware` method on route group in https://github.com/barryvdh/laravel-debugbar/blob/master/src/ServiceProvider.php#L79-L83 to attach it.

Should I do that?

**Comment by barryvdh** [comment]
I meant the Middleware method inside the constructor of the controller

**Comment by aik099** [comment]
I've understood you, but since you have 2 BaseController classes (one for Laravel and other for Lumen), then we can't use `$this->middleware(...` method unfortunately to cover both controllers.

The `->middleware(...` method on route/route group however should work for both Laravel/Lumen (I haven't used Lumen myself).

**Comment by aik099** [comment]
Not sure how it works internally, but maybe defining middleware on route/route group would work faster, because controller class instance isn't even created.

Anyway, should I change anything else?

**Comment by barryvdh** [comment]
defining it on the group would be better perhaps indeed.

**Comment by aik099** [comment]
Done.

**Comment by barryvdh** [comment]
Thanks! Let me know if you run into any problems with disabling now

**Comment by aik099** [comment]
I guess you can safely merge this into 2.4 branch as well to allow Laravel 5.4- users to benefit from this.

**Comment by barryvdh** [comment]
So the reason I didn't do this in the Middleware, is because it's a bit later in the request cycle. Not sure if this is still the best thing, because you could miss some queries/debug messages.

Could we also already boot in the serviceprovider? Downside is that in the event of disabling it on run-time, the listeners would be attached. But imho the useful cases are:

 - Enable on default for certain IP / circumstances (doesn't matter too much if we miss some stuff from early on)
 - Disable to avoid too much output but still in dev, so not extremely important that it's attached, as long as it doesn't output.

**Comment by aik099** [comment]
I've looked at code being executed since service provider boot and middleware execution and haven't found any SQLs being executed (or other things interesting to data collectors). That's why I thought disabling from middlewares is good thing.

**Pull request merged**
