### PR TITLE
Inertia support on ViewCollector

### LINKED ISSUE #1389: Feature request: Add support for Inertia.js
[Inertia.js](https://inertiajs.com/) allows you to serve frontend framework components (React/Vue/Svelte components) directly from the Laravel code. It's essentially the "glue" that can stick the frontend and backend together without the need for an API. 

However, Laravel + Inertia + React/Vue is not supported by the Laravel Debugbar. Since Inertia uses only one Blade template (which is essentially a master template), then the View tab in the Debugbar is pretty bare. It would be great if you could add support for Inertia, showing which component was rendered and which props were sent to said component.

### PR DESCRIPTION
**Pull request by erikn69**
Closes #1389
image

### CODE REVIEW

**Comment by MichaelNZ85** [comment]
What is the story with this? Looking forward to this feature

**Comment by parallels999** [comment]
>What is the story with this? 

Lack of reviews, no one has test it

**Comment by erikn69** [comment]
I did add my repositories to my `composer.json` to have my fixes on my local copy, this way
```json
"require-dev": {
    "barryvdh/laravel-debugbar": "^3.9.2"
},
"repositories":[
  {
      "type": "vcs",
      "url": "git@github.com:erikn69/php-debugbar.git"
  },
  {
      "type": "vcs",
      "url": "git@github.com:erikn69/laravel-debugbar.git"
  }
],
```
then `composer require "barryvdh/laravel-debugbar:^3.9.2" -W`
now must be working with this change, sometimes browser cache must be reload(`Ctrl + Shit + R`)

**Review by barryvdh — APPROVED** [review]

**Comment by barryvdh** [comment]
Please check dev-master with Inertia and let me know.

**Comment by barryvdh** [comment]
Or better, `3.9@dev`

**Comment by Dibbyo456** [comment]
Its working fine at `3.9@dev` 👍

**Pull request merged**
