### PR TITLE
Added check to ensure exceptions passed to debugbar are compatible with type-hint in php7 #497

### PR DESCRIPTION
**Pull request by jamiehd**

### CODE REVIEW

**Comment by jamiehd** [comment]
Sorry, forgot the phpdoc hint in the other one.

**Comment by barryvdh** [comment]
But this is still  listed to 2 levels deep.

**Comment by jamiehd** [comment]
Nope the function is recursive.

**Comment by barryvdh** [comment]
But looking at https://github.com/symfony/debug/blob/master/Exception/FatalThrowableError.php it will remove the previous exceptions right?
So should we just check if the actual exception is Throwable, and if so convert that.
And in php-debugbar check the previous exceptions, when added? So that we keep al information?

**Comment by jamiehd** [comment]
Yeah I've actually left a working implementation of that in the other pull request. I thought this was a better solution as it didn't make the symphony debug package a dependency of php-debugbar and also didn't require changes to both packages. I'm happy to submit my other fix as a pull request to each package if you'd rather. I've detailed it here: https://github.com/maximebf/php-debugbar/pull/276#issuecomment-225018643

**Comment by barryvdh** [comment]
I think that's probably better. But add a check for instanceof Throwable, instead of just `else`

**Comment by jamiehd** [comment]
Ok. And if it's not throwable do nothing with it?

**Comment by barryvdh** [comment]
I guess, but that *shouldn't* happen. It's just a bit more readable/clear what the intention is.

**Comment by barryvdh** [comment]
Or change it around like this:

```php
if($previous instanceof Throwable) {
	$previous = new FatalThrowableError($previous);
}
$this->addException($previous);
```

**Comment by jamiehd** [comment]
I thought about that, but do older versions of php have Throwable?

**Comment by barryvdh** [comment]
Oh sorry, that doesn't make sense, throwable matches all: https://3v4l.org/9n7DB

But we can check for \Error, even on php5: https://3v4l.org/jrKjc

**Comment by jamiehd** [comment]
Ok that makes sense to me, thanks.

**Pull request closed without merging**
