### PR TITLE
PHP8.2 explode(): Passing null to parameter #2 ($string) of type string is deprecated

### PR DESCRIPTION
**Pull request by grasebit**
Hi.

1. deprecated by PHP8.2
    * `local.WARNING: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /*/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php`
2. use PHP-CS-Fixer (LaravelPint) to config/debugbar.php

### CODE REVIEW

**Comment by erikn69** [comment]
```php
$this->app['config']->get('debugbar.remote_sites_path', '')
``` 
if null get returns the empty string (`''` is a fallback default), so, it would never be null
How did you get that error message?

**Comment by sebastiaanluca** [comment]
Can confirm the issue, even with an identical config file as in the repo.

```
// returns `null`
$this->app['config']->get('debugbar.remote_sites_path')

// returns `null`
$this->app['config']->get('debugbar.remote_sites_path', '')

// returns null 🤷‍♂️
$this->app['config']->get('debugbar.remote_sites_path', 'uhmmm')
```

It should fall back to the second parameter, but for some reason it doesn't and you get the deprecation warning in the log.

**Comment by grasebit** [comment]
env() function returns the value if the key exists.


```
// config/debugbar.php
'remote_sites_path' => env('DEBUGBAR_REMOTE_SITES_PATH')
// remote_sites_path is null

// src/LaravelDebugbar.php
$foo = $this->app['config']->get('debugbar.remote_sites_path', '');
// $foo is null

$bar = $this->app['config']->get('debugbar.remote_sites_path') ?? '';
// $bar is empty string
```


```
// config/debugbar.php
'remote_sites_path' => env('DEBUGBAR_REMOTE_SITES_PATH', '')
// remote_sites_path is empty string

// src/LaravelDebugbar.php
$foo = $this->app['config']->get('debugbar.remote_sites_path', '');
// $foo is empty string

$bar = $this->app['config']->get('debugbar.remote_sites_path') ?? '';
// $bar is empty string
```

**Comment by parallels999** [comment]
Maybe they would merge it if you removed the other unnecessary changes

**Pull request closed without merging**
